http:
  host:            0.0.0.0
  port:            3003
  read_timeout:    30  # Seconds
  write_timeout:   30  # Seconds

postgresql:
  request_timeout:    5                        # Seconds
  connection_timeout: 10                       # Seconds
  shutdown_timeout:   5                        # Seconds
